server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authservice
              uri: ${services.authservice-url}
              predicates:
                - Path=/api/v1/auth/**

            - id: userservice
              uri: ${services.userservice-url}
              predicates:
                - Path=/api/v1/users/**,/api/v1/cards/**

            - id: orderservice
              uri: ${services.orderservice-url}
              predicates:
                - Path=/api/v1/orders/**,/api/v1/items/**,/api/v1/order-items/**

            - id: paymentservice
              uri: ${services.paymentservice-url}
              predicates:
                - Path=/api/v1/payments/**

services:
  authservice-url: http://localhost:8081
  userservice-url: http://localhost:8082
  orderservice-url: http://localhost:8083
  paymentservice-url: http://localhost:8084

jwt:
  secret-key: "KZSHyaAUVhrpWoTlO7DkzqozsZBt62dxRNYPm53iRzA"